### ISSUE TITLE
Implement Image Reading Algorithm in OpenMP 

### ISSUE THREAD

**Issue by sbshah97** [IT-Department-Projects/PC-Project#1]
* Implement an Image Algorithm which takes an image as an input and parallel process the RGB Values in the given image matrix.
* Make sure to do this using only C++ and no bindings in the language! 
* Use valid resources from the Internet for the same and allow for more input values to be taken!

**Comment by kumiDa** [comment]
I have a few samples implemented in python, which is just needed to be implemented in c to aid the parallelization if you remember I have shared the code on hangouts...

**Comment by sbshah97** [comment]
I think we've already solved this in lab, I'll probably close this and add a serial k-means implementation
